spring:
  application:
    name: hydra-topic-service
  datasource:
    url: jdbc:h2:file:~/test
    username: roll
    password: tide
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    
server:
  port: 8889
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true