spring:
  application:
    name: hydra-topic-service
  datasource:
<<<<<<< HEAD
    url: jdbc:h2:file:~/test
    username: roll
    password: tide
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
=======
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@usfjavadb.cxzj3wk2fr9x.us-east-2.rds.amazonaws.com:1521:orcl
    username: project3
    password: p4ssw0rd
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    hibernate.ddl-auto: update
>>>>>>> dev
    
server:
  port: 8889
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
<<<<<<< HEAD
    preferIpAddress: true
=======
    preferIpAddress: true

  

#spring.datasource.url=jdbc:oracle:thin:@bamprod.cvoui7q38caj.us-east-2.rds.amazonaws.com:1521:orcl
#spring.datasource.username=bamproduser
#spring.datasource.password=revabam2017

#spring.datasource.url=jdbc:oracle:thin:@bamprod.cvoui7q38caj.us-east-2.rds.amazonaws.com:1521:ORCL
#spring.datasource.username=bamproduser
#spring.datasource.password=revabam2017

  

>>>>>>> dev
