INSERT INTO TOPIC(ID, NAME) VALUES (50, 'Java');
 
INSERT INTO TOPIC(ID, NAME) VALUES (51, 'SQL');

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1000, 'Loops', 'Completed', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1001, 'OOP', 'Missed', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1002, 'Inheritance', 'Missed', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1003, 'Select Queries', 'Planned', 51);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1004, 'Joins', 'Planned', 51);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1005, 'Polymorphism', 'Missed', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1006, 'Abstraction', 'Missed', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1007, 'Constraints', 'Planned', 51);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1008, 'Functions', 'Planned', 51);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1009, 'Procedures', 'Planned', 51);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1010, 'Static/Final Keyword', 'Completed', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1011, 'Exceptions and Errors', 'Planned', 50);

INSERT INTO SUBTOPIC(ID, NAME, STATUS, PARENT_TOPIC) VALUES (1012, 'File Handling', 'Planned', 50);
